### PR TITLE
chore(ci): add license check in ci

### PR DESCRIPTION
**Pull request by ajeetrai7**
This PR adds license-check in CI
How test was done:
- Added license check in Makefile to look for files having license .
- If license found then Build passes.
- Else Build fails.
The command to test license is `make license-check-go`

### CODE REVIEW

**Review by prateekpandey14 — APPROVED** [review]
lgtm

**Comment by kmova** [comment]
Hi @AJEETRAI707, thanks for the PR. Can you update the PR with details on how the code was tested? Did you try adding a file without a license check to see if the build fails?

**Comment by ajeetrai7** [comment]
> Hi @AJEETRAI707, thanks for the PR. Can you update the PR with details on how the code was tested? Did you try adding a file without a license check to see if the build fails?

@kmova I have added the PR with details and,Yes I have tried,by adding some files without having license and then build failed. Tested locally.

**Comment by ajeetrai7** [comment]
Closing this PR in favour of
https://github.com/openebs/api/pull/68

**Pull request closed without merging**
